version: '3.8'

services:
  valhelsia:
    image: itzg/minecraft-server
    container_name: valhelsia-server
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./data:/data
      - ./server.zip:/modpacks/server.zip
      - ../../common:/common
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/server.zip
      VERSION: 1.18.2
      MOTD: "§l§cValhelsia: Enhanced Vanilla§r (§5v1.18.2§r)"
      WHITELIST_FILE: /common/whitelist.json
      OPS_FILE: /common/ops.json
      OVERRIDE_SERVER_PROPERTIES: true
      OVERRIDE_WHITELIST: true
      MAX_TICK_TIME: -1
      PVP: false
      MEMORY: 24G
      ENABLE_AUTOPAUSE: TRUE
    restart: unless-stopped
    ports:
      - "25565:25565"

  valhelsia-backup:
    image: itzg/mc-backup
    container_name: valhelsia-backup
    environment:
      BACKUP_INTERVAL: "1h"
      MODPACK: "Valhelsia: Enhanced Vanilla (v1.18.2)"
      BACKUP_NAME: "valhelsia"
      PAUSE_IF_NO_PLAYERS: true
      POST_BACKUP_SCRIPT: |
        echo "Completed backup for $$MODPACK!"
        echo "Cleaning up superfluous backups..."
        ls -t /backups | tail -n +4 | xargs rm --
        echo "Cleaned! Only three newest backups remain."
    volumes:
    - ./data:/data:ro
    - /home/backups/valhelsia:/backups  # Set a path connected to cloud storage here for easy off-site backup!
    restart: unless-stopped
    network_mode: "service:valhelsia"